#! /bin/bash

while true
do
	if ping -c 1 www.google.com &> /dev/null
	then
		echo "Network check succed"
		sleep 4
	else
		echo "Network check failed, reconnecting"
		ifconfig eth0 down
		ifconfig eth0 up
	fi
done
