#! /bin/bash

WAIT_TIME=4
RECONNECTING_WAIT_TIME=7
INTERFACE=eth0

while test $# -gt 0
do
	case $1 in
		-w)
			if [[ -z "$2" ]]
			then
				echo "Missing param after -w wait time"
				exit 1
			fi
			WAIT_TIME=$2
			shift
			;;
		-r)
			if [[ -z "$2" ]]
			then
				echo "Missing param after -r reconnecting wait time"
				exit 1
			fi
			RECONNECTING_WAIT_TIME=$2
			shift
			;;
		-i)
			if [[ -z "$2" ]]
			then
				echo "Missing interface name"
				exit 1
			fi
			INTERFACE=$2
			shift
			;;
		*)
			echo "Unknown parameter $1"
			exit 1
	esac
	shift
done

while true
do
	if ping -c 1 www.google.com &> /dev/null
	then
		echo "Network check succed"
		sleep $WAIT_TIME
	else
		echo "Network check failed, reconnecting"
		ifconfig $INTERFACE down
		ifconfig $INTERFACE up
		sleep $RECONNECTING_WAIT_TIME
	fi
done
