#! /bin/bash

WAIT_TIME=4
RECONNECTING_WAIT_TIME=4
INTERFACE=eth0

while test $# -gt 0
do
	case $1 in
		-w)
			if [[ -z "$2" ]]
			then
				echo "Missing param after -w wait time"
				exit 1
			fi
			WAIT_TIME=$2
			shift
			;;
		-W)
			if [[ -z "$2" ]]
			then
				echo "Missing param after -W response wait time"
				exit 1
			fi
			RESPONSE_WAIT_TIME="-w $2 -W $2"
			shift
			;;
		-r)
			if [[ -z "$2" ]]
			then
				echo "Missing param after -r reconnecting wait time"
				exit 1
			fi
			RECONNECTING_WAIT_TIME=$2
			shift
			;;
		-i)
			if [[ -z "$2" ]]
			then
				echo "Missing interface name"
				exit 1
			fi
			INTERFACE=$2
			shift
			;;
		*)
			echo "Unknown parameter $1"
			exit 1
	esac
	shift
done

while true
do
	echo pinging...
	ping -c 1 $RESPONSE_WAIT_TIME 74.125.24.94 &> /dev/null &
	PID=$!
	echo $PID
	if ping -c 1 $RESPONSE_WAIT_TIME 74.125.24.94
	then
		echo "Network check succed"
		sleep $WAIT_TIME
	else
		echo "Network check failed, reconnecting"
		ifconfig $INTERFACE down
		echo "Recconect wait"
		sleep $RECONNECTING_WAIT_TIME
		echo "Recconect wait done"
		ifconfig $INTERFACE up
		echo "Recconect done"
	fi
done
